name: Convert LaTeX to DOCX

on:
  push:
    paths:
      - 'document.tex'  # Läuft nur, wenn document.tex aktualisiert wird

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Pandoc
        run: sudo apt-get install -y pandoc
      
      - name: Convert LaTeX to DOCX
        run: |
          echo "Converting document.tex to document.docx"
          pandoc document.tex -o document.docx
      
      - name: Commit DOCX file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add document.docx
          git commit -m "Generate DOCX from LaTeX" || echo "No changes to commit"
          git push
